GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/6143ab0304fca653f59155ad

###
DELETE http://localhost:3001/api/persons/614372dbf47e7a9062bff47c

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Moro Nani",
    "number": "113 2323 098"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Kikimaru",
    "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "113 2323 098"
}

###
PUT http://localhost:3001/api/persons/6143b17d1c083baf98b0e44d
Content-Type: application/json

{
    "id": "6143b17d1c083baf98b0e44d",
    "name": "Moro Nani",
    "number": "113 2323 098"
}